# Generated by Django 5.1.1 on 2024-09-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studeents',
            new_name='Students',
        ),
    ]
